### ISSUE TITLE
Problem: We cannot send a message

### ISSUE THREAD

**Issue by taotetek** [zeromq/gomq#8]
The first goal is simply sending a message. We are now exchanging protocol IDs and versions successfully, so that's a start.

Some good references:
* [ZMTP RFC](http://rfc.zeromq.org/spec:23)
* [libzmtp](https://github.com/zeromq/libzmtp)

To start with let's just get a pure Go implementation sending to a GoCZMQ Pull socket.  On the Go side, I've started by using a slightly modified Channeler API from GoCZMQ.   Working code should look like this:

```go
func main() {
        // create a dealer channeler
        push, err := NewPushChanneler("tcp://127.0.0.1:9999")
        if err != nil {
            panic(err)
        }
        defer push.Destroy()

        // send a hello message
        push.SendChan <- [][]byte{[]byte("Hello")}
}
```
I'm not that concerned with what the internals look like or if we want to refactor things later - I assume we'll have some false starts API wise and things will evolve over time as we go forward.

I also don't care about handling connections to multiple endpoints, load balancing, or any other zmq features until we hit the milestone of completing the handshake and sending a message.

Remember: solve one problem at a time.

**Comment by somdoron** [comment]
I have sometime this week, I will try to do it.

**Comment by taotetek** [comment]
@somdoron excellent!  I'm traveling this week and not sure how much time I'll have to hack on it again until the weekend.

**Comment by taotetek** [comment]
Status update:  We're sending messages from a gogozmq push socket to a gozmq pull socket (yay).  Going to make "sending from a gogozmq push to a gogozmq pull" the milestone for closing this issue.

**Comment by PSG-Luna** [comment]
Closed: We can send messages now!
